version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/mydb

  db:
    image: mongo
    ports:
      - "27017:27017"
